#!/bin/bash

find .work/terraform-provider-ovh/docs/{data-sources,guides,resources} -name '*.md' | while read f; do

# name=$(basename $f | sed -e 's#.md##g' -e 's#.html.md##g')
name=$f
cat > temp <<EOT
---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "$name Resource - terraform-provider-ovh"
subcategory: ""
description: |-
---
EOT

echo "Fixed $f"

mv temp $f
done
