/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1beta1 "github.com/edixos/provider-ovh/apis/cluster/additionalip/v1beta1"
	v1beta1cloud "github.com/edixos/provider-ovh/apis/cluster/cloud/v1beta1"
	v1beta1clouddiskarray "github.com/edixos/provider-ovh/apis/cluster/clouddiskarray/v1beta1"
	v1beta1databases "github.com/edixos/provider-ovh/apis/cluster/databases/v1beta1"
	v1beta1dedicatedserver "github.com/edixos/provider-ovh/apis/cluster/dedicatedserver/v1beta1"
	v1beta1dns "github.com/edixos/provider-ovh/apis/cluster/dns/v1beta1"
	v1beta1gateway "github.com/edixos/provider-ovh/apis/cluster/gateway/v1beta1"
	v1beta1iam "github.com/edixos/provider-ovh/apis/cluster/iam/v1beta1"
	v1beta1kube "github.com/edixos/provider-ovh/apis/cluster/kube/v1beta1"
	v1beta1lb "github.com/edixos/provider-ovh/apis/cluster/lb/v1beta1"
	v1beta1logs "github.com/edixos/provider-ovh/apis/cluster/logs/v1beta1"
	v1beta1me "github.com/edixos/provider-ovh/apis/cluster/me/v1beta1"
	v1beta1nas "github.com/edixos/provider-ovh/apis/cluster/nas/v1beta1"
	v1beta1network "github.com/edixos/provider-ovh/apis/cluster/network/v1beta1"
	v1beta1privatesql "github.com/edixos/provider-ovh/apis/cluster/privatesql/v1beta1"
	v1beta1registry "github.com/edixos/provider-ovh/apis/cluster/registry/v1beta1"
	v1beta1storage "github.com/edixos/provider-ovh/apis/cluster/storage/v1beta1"
	v1alpha1 "github.com/edixos/provider-ovh/apis/cluster/v1alpha1"
	v1beta1cluster "github.com/edixos/provider-ovh/apis/cluster/v1beta1"
	v1beta1vminstances "github.com/edixos/provider-ovh/apis/cluster/vminstances/v1beta1"
	v1beta1vrack "github.com/edixos/provider-ovh/apis/cluster/vrack/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1beta1.SchemeBuilder.AddToScheme,
		v1beta1cloud.SchemeBuilder.AddToScheme,
		v1beta1clouddiskarray.SchemeBuilder.AddToScheme,
		v1beta1databases.SchemeBuilder.AddToScheme,
		v1beta1dedicatedserver.SchemeBuilder.AddToScheme,
		v1beta1dns.SchemeBuilder.AddToScheme,
		v1beta1gateway.SchemeBuilder.AddToScheme,
		v1beta1iam.SchemeBuilder.AddToScheme,
		v1beta1kube.SchemeBuilder.AddToScheme,
		v1beta1lb.SchemeBuilder.AddToScheme,
		v1beta1logs.SchemeBuilder.AddToScheme,
		v1beta1me.SchemeBuilder.AddToScheme,
		v1beta1nas.SchemeBuilder.AddToScheme,
		v1beta1network.SchemeBuilder.AddToScheme,
		v1beta1privatesql.SchemeBuilder.AddToScheme,
		v1beta1registry.SchemeBuilder.AddToScheme,
		v1beta1storage.SchemeBuilder.AddToScheme,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1beta1cluster.SchemeBuilder.AddToScheme,
		v1beta1vminstances.SchemeBuilder.AddToScheme,
		v1beta1vrack.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
